# HTTP Sink with OAuth2 Client Credentials
# This example shows how to use OAuth2 Client Credentials flow
# The connector automatically manages token acquisition and caching

version: "2.2"
pipelines:
  - id: http-oauth2-pipeline
    status: running
    name: HTTP Sink with OAuth2
    description: Send records with OAuth2 Client Credentials authentication

    connectors:
      - id: kafka-source
        type: source
        plugin: builtin:kafka
        settings:
          servers: "localhost:9092"
          topics: "secure-events"
          groupID: "http-oauth2-group"

      - id: http-sink
        type: destination
        plugin: standalone:http
        name: http-oauth2-destination
        settings:
          url: "https://api.example.com/v2/webhooks"
          method: "POST"

          # OAuth2 Client Credentials
          authType: "oauth2"
          oauth2ClientId: "${OAUTH2_CLIENT_ID}"
          oauth2ClientSecret: "${OAUTH2_CLIENT_SECRET}"
          oauth2TokenUrl: "https://auth.example.com/oauth2/token"
          oauth2Scopes: "webhooks:write,events:send"

          # Retry configuration for production
          maxRetries: "5"
          retryBackoffBase: "2s"
          retryBackoffMax: "60s"
          retryOn5xx: "true"
          retryOn429: "true"
          retryOnNetworkErr: "true"

# Environment variables needed:
# export OAUTH2_CLIENT_ID="your-client-id"
# export OAUTH2_CLIENT_SECRET="your-client-secret"

# Note: The connector automatically:
# - Requests a new token on first use
# - Caches the token in memory
# - Requests a new token when expired
# - Thread-safe for concurrent requests
